version: '3'
services:
  postgres:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_DB: cartest
      POSTGRES_USER: cartest
      POSTGRES_PASSWORD: cartest
    volumes:
      - ./services/database/schema.sql
    ports:
      - 8005:5432
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.io
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 7005:80
